<?php $_code = $this->getMethodCode() ?>
<?php
$lastFourList = array();
$selected_cc_found = false;
if ($this->getInfoData('chasepaymentech_payment_id')) {
    $selected_cc = $this->getInfoData('chasepaymentech_payment_id');
} else {
    $selected_cc = Mage::getSingleton('customer/session')->getCustomer()->getChasePaymentechCustomerRefNum();
}
?>

<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display: none;">
	<?php if ($this->isLoggedIn() && $this->getStoredCards()) : ?>
    <li><h2 class="subtitle"><?php echo $this->__('Select a Credit Card'); ?></h2></li>
		<?php foreach ($this->getStoredCards() as $stored_card) : ?>
		<?php
			if ($stored_card->getCustomerRefNum() == $selected_cc) {
				$selected_cc_found = true;
			}
			$cc_num = $stored_card->getCcNumber();
			$lastFourList[] = substr($stored_card->getCcNumber(), -4);
		?>
			<li class="left-control">
				<div class="input-box">
					<input type="radio" name="payment[<?php echo $_code ?>_card]" onclick="document.getElementById('<?php echo $_code ?>_cc_new_card_form').style.display = 'none';" value="<?php echo $stored_card->getCustomerRefNum(); ?>" id="cc_saved_<?php echo $stored_card->getId(); ?>" class="radio" <?php echo ($stored_card->getId() == $selected_cc || $stored_card->getIsDefault()) ? 'checked="checked"' : ''; ?> />
				</div>
				<label for="cc_saved_<?php echo $stored_card->getId(); ?>" class="auto-width"><?php echo $this->__('Card Ending in: ') . substr($stored_card->getCcNumber(), -4) ?></label>
			</li>
		<?php endforeach;  ?>
	<?php endif;  ?>
	<li class="left-control">
        <?php if ($this->isLoggedIn() && $this->getStoredCards()) : ?>
		<div class="input-box">
			<input type="radio" name="payment[<?php echo $_code ?>_card]" value="NEWCARD" id="cc_enter_new_card" onclick="document.getElementById('<?php echo $_code ?>_cc_new_card_form').style.display = 'block';" <?php echo (!$this->isLoggedIn() || !$this->getStoredCards()) ? 'checked="checked"' : ''; ?> class="radio" />
		</div>
		<label for="cc_enter_new_card" class="auto-width"><?php echo $this->__('Enter a New Card') ?></label>
        <?php else : ?>
            <input type="hidden" name="payment[<?php echo $_code ?>_card]" value="NEWCARD" id="cc_enter_new_card" />
        <?php endif; ?>

		<ul id="<?php echo $_code ?>_cc_new_card_form" class="form-list" <?php echo ($this->isLoggedIn() && $this->getStoredCards()) ? 'style="display:none"' : ''; ?>>
			<li>
				<label for="<?php echo $_code ?>_cc_type" class="required"><em>*</em><?php echo $this->__('Card Type') ?></label>
				<div class="input-box">
					<select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" class="required-entry validate-cc-type-select">
						<option value=""><?php echo $this->__('--Please Select--') ?></option>
						<?php $_ccType = $this->getInfoData('cc_type') ?>
						<?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
							<option value="<?php echo $_typeCode ?>"<?php if ($_typeCode == $_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
						<?php endforeach ?>
					</select>
				</div>
			</li>
			<li>
				<label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Card Number') ?></label>
				<div class="input-box">
					<input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Card Number') ?>" class="input-text validate-cc-number validate-cc-type" value="" />
				</div>
			</li>
			<li id="<?php echo $_code ?>_cc_type_exp_div">
				<label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
				<div class="input-box">
					<div class="v-fix">
						<select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="month validate-cc-exp required-entry">
							<?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
							<?php foreach ($this->getCcMonths() as $k => $v): ?>
								<option value="<?php echo $k ? $k : '' ?>"<?php if ($k == $_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
							<?php endforeach ?>
						</select>
					</div>
                    <div class="v-fix">
						<?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
						<select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="year required-entry">
						<?php foreach ($this->getCcYears() as $k => $v): ?>
						<option value="<?php echo $k ? $k : '' ?>"<?php if ($k == $_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
						<?php endforeach ?>
						</select>
					</div>
				</div>
			</li>
			<?php echo $this->getChildHtml() ?>
			<li id="<?php echo $_code ?>_cc_type_cvv_div">
				<label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Verification') ?></label>
				<div class="input-box">
					<div class="v-fix">
						<input type="text" title="<?php echo $this->__('Verification') ?>" class="input-text cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" />
					</div>
					<a href="#" class="cvv-what-is-this" onclick="jQuery('#payment-tool-tip-close').show()><?php echo $this->__('What is this?') ?></a>
				</div>
			</li>
			<?php if ($this->isLoggedIn() && $this->isSaveOptional() && !$this->isGuest()) : ?>
				<li id="<?php echo $_code ?>_save_card_wrapper" class="control">
					<div class="input-box">
						<input type="checkbox" title="<?php echo $this->__('Save Card for Future Use') ?>" class="" id="<?php echo $_code ?>_save_card" name="payment[cc_save_card]" value="Yes" style="width: 15px;" />
					</div>
					<label for="<?php echo $_code ?>_save_card"><?php echo $this->__('Save this card for future use') ?></label>
				</li>
			<?php  endif; ?>
		</ul>
	</li>
 </ul>
