
<?php
/**
 * @see Mage_Payment_Block_Info
 */
?>
<?php echo $this->htmlEscape($this->getMethod()->getTitle()) ?>

<?php if ($_specificInfo = $this->getSpecificInformation()):?>
<table>
<?php foreach ($_specificInfo as $_label => $_value):?>
    <tr>
        <td><?php echo $this->escapeHtml($_label)?>:</td>
        <td><?php echo nl2br(implode($this->getValueAsArray($_value, true), "\n"))?></td>
    </tr>
<?php endforeach; ?>

<?php if (strlen($this->getInfo()->getCcAvsStatus())>0):?>
    <tr>
        <td>AVS: <?php echo $this->getInfo()->getCcAvsStatus() ?></td>
    </tr>
    <tr>
        <td>CVM: <?php echo $this->getInfo()->getCcCidStatus() ?></td>
    </tr>
    <tr>
        <td>Approval Code: <?php echo $this->getInfo()->getCcApproval() ?></td>
    </tr>
<?php endif;?>
</table>
<?php endif;?>

<?php echo $this->getChildHtml()?>
